apiVersion: apps/v1
kind: Deployment
metadata:
  name:my-ak-deployment
spec:
  replicas:1
  selector:
    matchLabels:
      app:angular-app
  template:
    metadata:
      labels:
        app:angular-app
    spec:
      containers:
        - name:my-angular-app
          image:tharindupro/mywebapp:latest
          imagePullPolicy:Always
          ports:
            - containerPort: 8888

apiVersion: v1
kind: Service
metadata:
  name: angular-app-svc
spec:
  selector:
    app: angular-app
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 8888
  type: LoadBalancer
